### ISSUE TITLE
Fix links when clicking pool name

### ISSUE THREAD

**Issue by SebastienGllmt** [Emurgo/adapools-yoroi-frontend#8]
Clicking on a the name of a pool from inside Yoroi will try and open the link inside the iframe which will throw an error. It should instead open the URL in a new link

To do this, the URL should specify `target="_blank"`

Note: at the time of posting, Yoroi doesn't allow any links at all (even if they open in a new tab instead of the iframe)
We can choose to allow this by adding `allow-popups` to the iframe sandbox permissions. The downside of doing this is that if our website gets hacked, they could popup some malicious website.

Another way we could solve this is that when you click on a link, it gets sent to Yoroi via `postMessage`, and then Yoroi asks the user to confirm they want to open` https://website-name-here` in a dialog

**Comment by cardanians** [comment]
I fixed this issue (target blank) some time ago :)
